communiteq_powertools:
  communiteq_powertools_enabled:
    default: false
    client: false
  communiteq_powertools_sort_templates_alphabetically:
    default: false
    client: false
    hidden: true
  communiteq_powertools_post_delete_time_limit_enabled:
    default: false
    client: false
    hidden: true
  communiteq_powertools_post_delete_time_limit_hours:
    default: 24
    client: false
    hidden: true
  communiteq_powertools_auto_auto_grid_enabled:
    default: false
    client: false
    hidden: true
  communiteq_powertools_auto_auto_grid_min_images:
    default: 2
    client: false
    hidden: true
  communiteq_powertools_force_moderation_for_groups:
    default: ""
    client: false
    hidden: true
    type: group_list
    allow_any: false
    refresh: true
  communiteq_powertools_force_moderation_new_topics_for_groups:
    default: ""
    client: false
    hidden: true
    type: group_list
    allow_any: false
    refresh: true
